In [2]:
import numpy as np
data = np.arange(2,50,3)
print(data)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [8]:
#Question 2
list1 = []
list2 = []
for i in range(0,5):
    val = int(input('List1: '))
    list1.append(val)
#print(type(list1))
for i in range(0,5):
    val = int(input('List2: '))
    list2.append(val)
#print(list1,list2)
arr1 = np.array(list1)
arr2 = np.array(list2)
#print(type(arr))
con = np.concatenate((arr1, arr2))
print(con)
con.sort()
print(con)

List1: 12
List1: 21
List1: 32
List1: 23
List1: 65
List2: 45
List2: 85
List2: 98
List2: 94
List2: 20
[12 21 32 23 65 45 85 98 94 20]
[12 20 21 23 32 45 65 85 94 98]


In [20]:
#Question 3
x = np.zeros((3, 3))
print(x)
print('Dimension: ',x.ndim)
print('Size: ',x.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Dimension:  2
Size:  9


In [28]:
#Question 4
x = np.array([1, 2])
print(x)
print('Shape:',x.shape)
print('Dimension:', x.ndim)
y = np.expand_dims(x, axis=0)
print('Shape:',y.shape)
print('Dimension:', y.ndim)

[1 2]
Shape: (2,)
Dimension: 1
Shape: (1, 2)
Dimension: 2


In [32]:
#Question 5
a1 = np.array([[1,2], [2,3], [3,4]])
a2 = np.array([[2,4], [3,9], [4,16]])
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

[[ 1  2]
 [ 2  3]
 [ 3  4]
 [ 2  4]
 [ 3  9]
 [ 4 16]]
[[ 1  2  2  4]
 [ 2  3  3  9]
 [ 3  4  4 16]]


In [39]:
#Question 6
data1 = np.array([[1,2,3,8], [2,3,4,1], [3,4,5,2]])
print(np.unique(data1, return_counts = True))

(array([1, 2, 3, 4, 5, 8]), array([2, 3, 3, 2, 1, 1], dtype=int64))
